name: run_job_2

on:
  schedule:
    - cron: "0 11 * * 6" # Every Saturday at 11am UTC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  run_thingy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # retrieve secrets from github
    env:
        RENV_PATHS_ROOT: ~/.local/share/renv
        SECRETS: ${{ secrets.SECRETS }}
        COVID_EMAIL_UPDATE_PASSWORD: ${{ secrets.COVID_EMAIL_UPDATE_PASSWORD }}
    #
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      # install renv package
      - run: R -e 'install.packages(c("renv", "devtools"))'
      - run: sudo apt install libsodium-dev #necessary software to implement incryption
      - run: R -e 'devtools::install_github("jedisct1/libsodium")'
      - if: runner.os == 'macOS'
        run: brew install --cask xquartz
      # set up cache
      - name: Cache packages
        uses: actions/cache@v1
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      # install c++ dependencies and install necessary packages
      - run: R -e 'renv::restore()'
      # execute Rscript
      - name: Running script
        run: Rscript makesendfigures.R
